const claves = { perfil: 'los_robles_perfil_prueba', residentes: 'los_robles_residentes', movimientos: 'los_robles_movimientos', caja: 'los_robles_caja_chica', historialCaja: 'los_robles_historial_caja_chica', movimientosCaja: 'los_robles_movimientos_caja', ajustes: 'los_robles_ajustes_manuales' };
const obtener = (clave, valor = []) => { try { return JSON.parse(localStorage.getItem(clave)) ?? valor; } catch { return valor; } };
const guardar = (clave, valor) => localStorage.setItem(clave, JSON.stringify(valor));
export const obtenerPerfilPrueba = () => localStorage.getItem(claves.perfil) || 'TestPresidente';
export const guardarPerfilPrueba = perfil => localStorage.setItem(claves.perfil, perfil);
export const obtenerResidentes = () => obtener(claves.residentes);
export const guardarResidentes = residentes => guardar(claves.residentes, residentes);
const normalizarRol = rol => String(rol || '').replace(/\s/g, '').toLowerCase();
export const obtenerResidentesPorRol = rol => obtenerResidentes().filter(residente => residente.mesa === true && residente.estatus !== 'Inactiva' && normalizarRol(residente.rol) === normalizarRol(rol));
export const obtenerTesoreros = () => obtenerResidentesPorRol('Tesorero');
export const obtenerAuxiliaresTesoreria = () => obtenerResidentesPorRol('AuxiliarTesoreria');
export const obtenerResidentePorId = id => obtenerResidentes().find(residente => residente.id === id) || null;
export const obtenerMovimientos = () => obtener(claves.movimientos);
export const guardarMovimientos = movimientos => guardar(claves.movimientos, movimientos);
export const obtenerCajaChica = () => obtener(claves.caja, null);
export const guardarCajaChica = caja => guardar(claves.caja, caja);
export const obtenerHistorialCajaChica = () => obtener(claves.historialCaja);
export const guardarHistorialCajaChica = historial => guardar(claves.historialCaja, historial);
export const obtenerMovimientosCaja = () => obtener(claves.movimientosCaja);
export const guardarMovimientosCaja = movimientos => guardar(claves.movimientosCaja, movimientos);
export const agregarMovimientoCaja = movimiento => { const movimientos = obtenerMovimientosCaja(); guardarMovimientosCaja([...movimientos, movimiento]); };
export const obtenerAjustesManuales = () => obtener(claves.ajustes);
export const guardarAjustesManuales = ajustes => guardar(claves.ajustes, ajustes);
export const obtenerHistorialAjustesFinancieros = () => obtener('los_robles_historial_ajustes_financieros');
export const guardarHistorialAjustesFinancieros = historial => guardar('los_robles_historial_ajustes_financieros', historial);
